name: document
on:
  push:
    branches:
      - docs
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: AdvancedProductivity/Gable
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd ./document && yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist/